apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excalidraw1
  namespace: argocd
spec:
  project: default
  source:
    chart: excalidraw
    repoURL: 'git@github.com:Riham2391998/excalidraw.git'
    path: 'charts/excalidraw'
    targetRevision: HEAD
    helm:
      releaseName: excalidraw
  destination:
    server: "https://kubernetes.default.svc"
    namespace: excalidraw
